config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get '/threads/:id', to: 'posts#new', as: 'thread'

  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'posts#index'
  devise_for :users
  resources :users
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :code, presence: true
  validates_uniqueness_of :code, scope: :user_id
  after_create :set_attributes, :forbidden_words
  scope :by_virtual_code, -> { order(:virtual_code) }
  scope :zero_level, -> { where("code_level = 0")}

  def self.new_thread_code( user, thread )
    if thread.nil?
      (Post.where( user: user ).zero_level.last.try(:code).to_i + 1).to_s
    else
      unless ( sub_level_posts = Post.where( user: user ).where( code_level: thread.code_level + 1 ).where( super_code: thread.code ) ).blank?
        array_code = sub_level_posts.where( super_code: thread.code ).by_virtual_code.last.code.split('.')
        last_arrray_item = (array_code.pop.to_i + 1).to_s
        (array_code << last_arrray_item).join('.')
      else
        thread.code << '.1'
      end
    end
  end

  def is_zero_level?
    self.code_level == 0
  end

  private

  def forbidden_words
    return true if self.is_zero_level?
    return true if self.message.blank?
    message = Post.where( user: self.user ).where( code_group: self.code_group ).where( code_level: 0 ).first.try(:message)
    return true unless message
    array_menssage = message.split(' ')
    if array_menssage.shift == 'comentarios' && array_menssage.shift == 'proibidos:'
     array_menssage.each do |e|
       self.message.gsub!(e, 'xxxx')
     end
     self.save!
    end
  end

  def set_attributes
    create_virtual_code
    set_code_level
    set_code_group
    set_super_code
    self.save!
  end

  def set_super_code
    if self.is_zero_level?
      self.super_code = '0'
    else
      array_code = self.code.split('.')
      array_code.pop
      self.super_code = array_code.join('.')
    end
  end

  def set_code_group
    self.code_group = self.virtual_code[0,3]
  end

  def set_code_level
    self.code_level = self.virtual_code.count('.')
  end

  def create_virtual_code
    self.virtual_code = self.code.split('.').map do |e|
      e.prepend(zeros_to_prepend(e))
    end.join('.')
  end

  def zeros_to_prepend( str_number )
    return '' if (number = str_number.to_i) >= 100 || str_number.length >= 3
    return '0' if number >= 10
    '00' if number >= 0
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if params[:post_id].blank?
      @first_index_page = true
      @posts = Post.where( user: current_user ).zero_level.by_virtual_code.page params[:page]
      new_code = Post.new_thread_code( current_user, nil )
      @post = Post.new
      @post.code = new_code
    else
      @first_index_page = false
      code_group = Post.find(params[:post_id]).code_group
      @posts = Post.where( user: current_user ).where( code_group: code_group ).by_virtual_code.page params[:page]
    end
  end

  def show
  end

  def new
    thread = Post.find(params[:id])
    new_code = Post.new_thread_code( current_user, thread )
    @post = Post.new
    @post.code = new_code
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Thread was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Thread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:code, :virtual_code, :user_id, :message)
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def left_spaces(post)
    post.code_level.to_i * 20
  end

  def left_spaces_style(post)
    "display:inline-block; width: #{left_spaces(post)}px;"
  end

end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :code, value: @post.code %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit 'submit thread' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if current_user %>
  <h1>Threads</h1>
  <% unless @post.blank? %>
    <%= render partial: 'form', locals: {thread: nil} %>
  <% end %>
  <table class="table table-striped table-bordered table-condensed table-sm">
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <th>
            <span style="<%= left_spaces_style(post) %>"></span>
            <%= link_to "#{post.code}. #{post.created_at}", posts_path( post_id: post.id ) %>
            <% unless @first_index_page %>
              <%= link_to "reply", thread_path(id: post.id)  %>
            <% end %>
          </th>
          <td><%= post.message %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @posts %>
<% else %>
  <%= render partial: 'pages/app_info' %>
<% end %>
<br>

app/views/posts/new.html.erb
<%= render partial: 'form' %>

app/views/posts/show.html.erb
<p>
  <strong>Message:</strong>
  <%= @post.message %>
</p>

<%= link_to 'Index', posts_path %>